<?php
namespace HMP\Admin;

use HMP\Events\Event_Processor;
use HMP\Lifecycle;
use HMP\MemberPress\Revocation_Service;
use HMP\Repositories\Activation_Repository;
use HMP\Repositories\Event_Repository;
use HMP\Repositories\Mapping_Repository;
use HMP\Settings;
use HMP\Upgrader;
use HMP\Webhook\Payload_Normalizer;

if ( ! defined( 'ABSPATH' ) ) { exit; }

class Tools {
	private Event_Repository $events; private Mapping_Repository $mappings; private Activation_Repository $activations; private Event_Processor $processor; private Payload_Normalizer $normalizer;
	public function __construct( Event_Repository $events, Mapping_Repository $mappings, Activation_Repository $activations, Event_Processor $processor, Payload_Normalizer $normalizer, Revocation_Service $revocations ) { $this->events=$events; $this->mappings=$mappings; $this->activations=$activations; $this->processor=$processor; $this->normalizer=$normalizer; }
	public function register(): void { add_action( 'admin_post_hmp_manual_json', array($this,'manual_json') ); add_action( 'admin_post_hmp_manual_activation', array($this,'manual_activation') ); add_action( 'admin_post_hmp_run_grace', array($this,'run_grace') ); add_action( 'admin_post_hmp_test_endpoint', array($this,'test_endpoint') ); add_action( 'admin_post_hmp_delete_diagnostics', array($this,'delete_diagnostics') ); }
	private function auth( string $nonce ): void { if ( ! current_user_can('manage_options') ) wp_die( esc_html__('Not allowed.','hotmart-memberpress-pro') ); check_admin_referer($nonce); }
	private function redirect( string $notice, int $event=0 ): void { wp_safe_redirect(add_query_arg(array_filter(array('page'=>'hotmart-memberpress-pro-tools','hmp_notice'=>$notice,'event_id'=>$event)),admin_url('admin.php'))); exit; }
	public function manual_json(): void { $this->auth('hmp_manual_json'); $raw=wp_unslash($_POST['payload']??''); $data=json_decode($raw,true); if(!is_array($data)) $this->redirect('invalid_json'); $n=$this->normalizer->normalize($data); if(empty($n['event'])) $this->redirect('missing_event'); $key='manual_'.hash('sha256',wp_json_encode($n)); $existing=$this->events->find_by_event_key($key); if($existing) $this->redirect('duplicate',(int)$existing->id); $id=$this->events->insert(array('event_key'=>$key,'hotmart_event'=>$n['event'],'transaction_code'=>$n['transaction'],'subscription_code'=>$n['subscription'],'buyer_email'=>$n['buyer_email'],'payload'=>wp_json_encode($data),'source'=>'manual_json')); if(is_wp_error($id)) $this->redirect('database_error'); $this->processor->process((int)$id,$n); $this->redirect('processed',(int)$id); }
	public function manual_activation(): void { $this->auth('hmp_manual_activation'); $email=sanitize_email($_POST['email']??''); $membership=absint($_POST['membership_id']??0); $code=sanitize_text_field($_POST['transaction_code']??''); $reason=sanitize_textarea_field($_POST['reason']??''); if(!is_email($email)||!$membership||!$code||!$reason||!class_exists('MeprTransaction')) $this->redirect('invalid_activation'); if($this->activations->exists($code,$membership)) $this->redirect('duplicate_activation'); $user=get_user_by('email',$email); if(!$user){$id=wp_insert_user(array('user_login'=>sanitize_user(strtok($email,'@').'_'.substr(hash('sha256',$email),0,6),true),'user_email'=>$email,'user_pass'=>wp_generate_password(32,true,true),'role'=>get_option('default_role','subscriber'))); if(is_wp_error($id)) $this->redirect('user_error'); $user=get_user_by('id',$id);} $starts=sanitize_text_field($_POST['starts_at']??current_time('mysql',true)); $expires=sanitize_text_field($_POST['expires_at']??''); try{$txn=new \MeprTransaction();$txn->user_id=$user->ID;$txn->product_id=$membership;$txn->gateway=\MeprTransaction::$manual_gateway_str;$txn->status=\MeprTransaction::$complete_str;$txn->txn_type=\MeprTransaction::$payment_str;$txn->trans_num='hmp_manual_'.substr(hash('sha256',$code.'|'.$membership),0,40);$txn->amount=(float)($_POST['amount']??0);$txn->total=$txn->amount;$txn->created_at=$starts;$txn->expires_at=$expires?:null;$txn_id=(int)$txn->store(true);}catch(\Throwable $e){$this->redirect('memberpress_error');} $result=$this->activations->insert(array('user_id'=>$user->ID,'membership_id'=>$membership,'memberpress_transaction_id'=>$txn_id,'hotmart_transaction'=>$code,'hotmart_subscription'=>sanitize_text_field($_POST['subscription_code']??'')?:null,'status'=>'active','starts_at'=>$starts,'expires_at'=>$expires?:null,'source'=>'manual','manual_admin_id'=>get_current_user_id(),'manual_reason'=>$reason,'last_event'=>'MANUAL_ACTIVATION','last_event_at'=>current_time('mysql',true))); $this->redirect(is_wp_error($result)?'database_error':'activation_created'); }
	public function run_grace(): void { $this->auth('hmp_run_grace'); $this->redirect('grace_'.Lifecycle::process_grace()); }
	public function delete_diagnostics(): void { $this->auth('hmp_delete_diagnostics'); $this->redirect('diagnostics_deleted_'.$this->events->delete_diagnostics()); }
	public function test_endpoint(): void {
		$this->auth('hmp_test_endpoint');
		$original_enabled = get_option('hmp_webhook_enabled'); $results=array();
		try {
			update_option('hmp_webhook_enabled',0); $results['disabled']=$this->request_diagnostic('wrong');
			update_option('hmp_webhook_enabled',1); $results['invalid_token']=$this->request_diagnostic('wrong');
			$token=(string)Settings::get('hmp_hottok'); $results['valid_payload']=$token!==''?$this->request_diagnostic($token):array('http'=>401,'response'=>'HOTTOK not configured','event_id'=>0,'status'=>'not_created');
		} finally { update_option('hmp_webhook_enabled',$original_enabled); }
		set_transient('hmp_diagnostic_result_'.get_current_user_id(),$results,5*MINUTE_IN_SECONDS); $this->redirect('endpoint_test_complete');
	}
	private function request_diagnostic(string $token): array {
		$server=rest_get_server(); if(empty($server->get_routes()['/hmp/v1/webhook'])) do_action('rest_api_init'); $request=new \WP_REST_Request('POST','/hmp/v1/webhook'); $request->set_header('content-type','application/json'); $request->set_header('x-hotmart-hottok',$token); $id='diag-'.wp_generate_uuid4(); $request->set_body(wp_json_encode(array('id'=>$id,'event'=>'HMP_DIAGNOSTIC','creation_date'=>time()))); $response=rest_do_request($request); $data=$response->get_data(); $event_id=absint($data['event_id']??0); $event=$event_id?$this->events->find_by_id($event_id):null; return array('http'=>$response->get_status(),'response'=>wp_json_encode($data),'event_id'=>$event_id,'status'=>$event?$event->status:'not_created');
	}
	public function render(): void { if(!current_user_can('manage_options')) return; global $wpdb; $tables=array($wpdb->prefix.'hmp_events',$wpdb->prefix.'hmp_activations',$wpdb->prefix.'hmp_mappings'); ?>
	<div class="wrap"><h1><?php esc_html_e('Hotmart MemberPress Tools','hotmart-memberpress-pro');?></h1><?php if(isset($_GET['hmp_notice'])):?><div class="notice notice-info"><p><?php echo esc_html(sanitize_text_field($_GET['hmp_notice']));?><?php if(isset($_GET['event_id'])):?> — <a href="<?php echo esc_url(admin_url('admin.php?page=hotmart-memberpress-pro-webhooks&view_event='.absint($_GET['event_id'])));?>"><?php esc_html_e('View event','hotmart-memberpress-pro');?></a><?php endif;?></p></div><?php endif;?>
	<h2><?php esc_html_e('Process JSON','hotmart-memberpress-pro');?></h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="hmp_manual_json"><?php wp_nonce_field('hmp_manual_json');?><textarea name="payload" rows="10" class="large-text code" required></textarea><?php submit_button(__('Process JSON','hotmart-memberpress-pro'));?></form>
	<h2><?php esc_html_e('Manual activation','hotmart-memberpress-pro');?></h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="hmp_manual_activation"><?php wp_nonce_field('hmp_manual_activation');?><table class="form-table"><?php foreach(array('email','membership_id','transaction_code','subscription_code','starts_at','expires_at','amount','reason') as $field):?><tr><th><label for="<?php echo esc_attr($field);?>"><?php echo esc_html(ucwords(str_replace('_',' ',$field)));?></label></th><td><input class="regular-text" id="<?php echo esc_attr($field);?>" name="<?php echo esc_attr($field);?>" <?php echo in_array($field,array('email','membership_id','transaction_code','starts_at','reason'),true)?'required':'';?>></td></tr><?php endforeach;?></table><?php submit_button(__('Create activation','hotmart-memberpress-pro'));?></form>
	<h2><?php esc_html_e('Diagnostics','hotmart-memberpress-pro');?></h2><?php $schema=Upgrader::verify_schema(); $diagnostic=get_transient('hmp_diagnostic_result_'.get_current_user_id()); $memberpress=defined('MEPR_VERSION')?MEPR_VERSION:(class_exists('MeprAppCtrl')?'available':'unavailable'); $wpcli=is_executable('/usr/local/bin/wp')||is_executable('/usr/bin/wp')?'available':'not detected'; $report=array('PHP_VERSION='.PHP_VERSION,'PHP_SAPI='.PHP_SAPI,'mysqli='.(extension_loaded('mysqli')?'yes':'no'),'pdo_mysql='.(extension_loaded('pdo_mysql')?'yes':'no'),'WordPress='.get_bloginfo('version'),'MemberPress='.$memberpress,'Plugin='.HMP_VERSION,'Schema='.(string)get_option('hmp_db_version','0'),'Table prefix='.$wpdb->prefix);?><table class="widefat striped"><tbody><tr><th>Plugin / schema expected / installed</th><td><?php echo esc_html(HMP_VERSION.' / '.HMP_DB_VERSION.' / '.$schema['installed']);?></td></tr><tr><th>Schema status</th><td><?php echo $schema['current']?'updated':'pending';?></td></tr><tr><th>Missing columns</th><td><?php echo esc_html($schema['missing']?implode(', ',$schema['missing']):'none');?></td></tr><tr><th>Last migration error</th><td><?php echo esc_html(Upgrader::last_error()?:'none');?></td></tr><tr><th>PHP web / SAPI</th><td><?php echo esc_html(PHP_VERSION.' / '.PHP_SAPI);?></td></tr><tr><th>mysqli in PHP web</th><td><?php echo extension_loaded('mysqli')?'loaded':'not loaded';?></td></tr><tr><th>PDO MySQL in PHP web</th><td><?php echo extension_loaded('pdo_mysql')?'loaded':'not loaded';?></td></tr><tr><th>WordPress database connection</th><td><?php echo empty($wpdb->last_error)?'connected':'error';?></td></tr><tr><th>WP-CLI</th><td><?php echo esc_html($wpcli);?></td></tr><tr><th>MemberPress</th><td><?php echo esc_html($memberpress);?></td></tr></tbody></table>
	<textarea class="large-text code" rows="10" readonly><?php echo esc_textarea(implode("\n",$report));?></textarea>
	<?php if(is_array($diagnostic)):?><h3>Endpoint test</h3><pre><?php echo esc_html(wp_json_encode($diagnostic,JSON_PRETTY_PRINT));?></pre><?php endif;?>
	<?php foreach(array('hmp_run_migration'=>'Run migration now','hmp_test_endpoint'=>'Test endpoint','hmp_delete_diagnostics'=>'Delete diagnostic events','hmp_run_grace'=>'Run grace expirations') as $action=>$label):?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" style="display:inline-block;margin-right:8px"><input type="hidden" name="action" value="<?php echo esc_attr($action);?>"><?php wp_nonce_field($action);submit_button(__($label,'hotmart-memberpress-pro'),'secondary','submit',false);?></form><?php endforeach;?></div><?php }
}
