<?php
namespace HMP\Admin;

use HMP\Events\Event_Processor;
use HMP\Lifecycle;
use HMP\MemberPress\Revocation_Service;
use HMP\Repositories\Activation_Repository;
use HMP\Repositories\Event_Repository;
use HMP\Repositories\Mapping_Repository;
use HMP\Settings;
use HMP\Webhook\Payload_Normalizer;

if ( ! defined( 'ABSPATH' ) ) { exit; }

class Tools {
	private Event_Repository $events; private Mapping_Repository $mappings; private Activation_Repository $activations; private Event_Processor $processor; private Payload_Normalizer $normalizer;
	public function __construct( Event_Repository $events, Mapping_Repository $mappings, Activation_Repository $activations, Event_Processor $processor, Payload_Normalizer $normalizer, Revocation_Service $revocations ) { $this->events=$events; $this->mappings=$mappings; $this->activations=$activations; $this->processor=$processor; $this->normalizer=$normalizer; }
	public function register(): void { add_action( 'admin_post_hmp_manual_json', array($this,'manual_json') ); add_action( 'admin_post_hmp_manual_activation', array($this,'manual_activation') ); add_action( 'admin_post_hmp_run_grace', array($this,'run_grace') ); }
	private function auth( string $nonce ): void { if ( ! current_user_can('manage_options') ) wp_die( esc_html__('Not allowed.','hotmart-memberpress-pro') ); check_admin_referer($nonce); }
	private function redirect( string $notice, int $event=0 ): void { wp_safe_redirect(add_query_arg(array_filter(array('page'=>'hotmart-memberpress-pro-tools','hmp_notice'=>$notice,'event_id'=>$event)),admin_url('admin.php'))); exit; }
	public function manual_json(): void { $this->auth('hmp_manual_json'); $raw=wp_unslash($_POST['payload']??''); $data=json_decode($raw,true); if(!is_array($data)) $this->redirect('invalid_json'); $n=$this->normalizer->normalize($data); if(empty($n['event'])) $this->redirect('missing_event'); $key='manual_'.hash('sha256',wp_json_encode($n)); $existing=$this->events->find_by_event_key($key); if($existing) $this->redirect('duplicate',(int)$existing->id); $id=$this->events->insert(array('event_key'=>$key,'hotmart_event'=>$n['event'],'transaction_code'=>$n['transaction'],'subscription_code'=>$n['subscription'],'buyer_email'=>$n['buyer_email'],'payload'=>wp_json_encode($data),'source'=>'manual_json')); if(is_wp_error($id)) $this->redirect('database_error'); $this->processor->process((int)$id,$n); $this->redirect('processed',(int)$id); }
	public function manual_activation(): void { $this->auth('hmp_manual_activation'); $email=sanitize_email($_POST['email']??''); $membership=absint($_POST['membership_id']??0); $code=sanitize_text_field($_POST['transaction_code']??''); $reason=sanitize_textarea_field($_POST['reason']??''); if(!is_email($email)||!$membership||!$code||!$reason||!class_exists('MeprTransaction')) $this->redirect('invalid_activation'); if($this->activations->exists($code,$membership)) $this->redirect('duplicate_activation'); $user=get_user_by('email',$email); if(!$user){$id=wp_insert_user(array('user_login'=>sanitize_user(strtok($email,'@').'_'.substr(hash('sha256',$email),0,6),true),'user_email'=>$email,'user_pass'=>wp_generate_password(32,true,true),'role'=>get_option('default_role','subscriber'))); if(is_wp_error($id)) $this->redirect('user_error'); $user=get_user_by('id',$id);} $starts=sanitize_text_field($_POST['starts_at']??current_time('mysql',true)); $expires=sanitize_text_field($_POST['expires_at']??''); try{$txn=new \MeprTransaction();$txn->user_id=$user->ID;$txn->product_id=$membership;$txn->gateway=\MeprTransaction::$manual_gateway_str;$txn->status=\MeprTransaction::$complete_str;$txn->txn_type=\MeprTransaction::$payment_str;$txn->trans_num='hmp_manual_'.substr(hash('sha256',$code.'|'.$membership),0,40);$txn->amount=(float)($_POST['amount']??0);$txn->total=$txn->amount;$txn->created_at=$starts;$txn->expires_at=$expires?:null;$txn_id=(int)$txn->store(true);}catch(\Throwable $e){$this->redirect('memberpress_error');} $result=$this->activations->insert(array('user_id'=>$user->ID,'membership_id'=>$membership,'memberpress_transaction_id'=>$txn_id,'hotmart_transaction'=>$code,'hotmart_subscription'=>sanitize_text_field($_POST['subscription_code']??'')?:null,'status'=>'active','starts_at'=>$starts,'expires_at'=>$expires?:null,'source'=>'manual','manual_admin_id'=>get_current_user_id(),'manual_reason'=>$reason,'last_event'=>'MANUAL_ACTIVATION','last_event_at'=>current_time('mysql',true))); $this->redirect(is_wp_error($result)?'database_error':'activation_created'); }
	public function run_grace(): void { $this->auth('hmp_run_grace'); $this->redirect('grace_'.Lifecycle::process_grace()); }
	public function render(): void { if(!current_user_can('manage_options')) return; global $wpdb; $tables=array($wpdb->prefix.'hmp_events',$wpdb->prefix.'hmp_activations',$wpdb->prefix.'hmp_mappings'); ?>
	<div class="wrap"><h1><?php esc_html_e('Hotmart MemberPress Tools','hotmart-memberpress-pro');?></h1><?php if(isset($_GET['hmp_notice'])):?><div class="notice notice-info"><p><?php echo esc_html(sanitize_text_field($_GET['hmp_notice']));?><?php if(isset($_GET['event_id'])):?> — <a href="<?php echo esc_url(admin_url('admin.php?page=hotmart-memberpress-pro-webhooks&view_event='.absint($_GET['event_id'])));?>"><?php esc_html_e('View event','hotmart-memberpress-pro');?></a><?php endif;?></p></div><?php endif;?>
	<h2><?php esc_html_e('Process JSON','hotmart-memberpress-pro');?></h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="hmp_manual_json"><?php wp_nonce_field('hmp_manual_json');?><textarea name="payload" rows="10" class="large-text code" required></textarea><?php submit_button(__('Process JSON','hotmart-memberpress-pro'));?></form>
	<h2><?php esc_html_e('Manual activation','hotmart-memberpress-pro');?></h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="hmp_manual_activation"><?php wp_nonce_field('hmp_manual_activation');?><table class="form-table"><?php foreach(array('email','membership_id','transaction_code','subscription_code','starts_at','expires_at','amount','reason') as $field):?><tr><th><label for="<?php echo esc_attr($field);?>"><?php echo esc_html(ucwords(str_replace('_',' ',$field)));?></label></th><td><input class="regular-text" id="<?php echo esc_attr($field);?>" name="<?php echo esc_attr($field);?>" <?php echo in_array($field,array('email','membership_id','transaction_code','starts_at','reason'),true)?'required':'';?>></td></tr><?php endforeach;?></table><?php submit_button(__('Create activation','hotmart-memberpress-pro'));?></form>
	<h2><?php esc_html_e('Diagnostics','hotmart-memberpress-pro');?></h2><table class="widefat striped"><tbody><tr><th>Plugin / DB</th><td><?php echo esc_html(HMP_VERSION.' / '.get_option('hmp_db_version','—'));?></td></tr><tr><th>WordPress / PHP</th><td><?php echo esc_html(get_bloginfo('version').' / '.PHP_VERSION);?></td></tr><tr><th>MemberPress</th><td><?php echo class_exists('MeprTransaction')?'OK':'Unavailable';?></td></tr><tr><th>Tables</th><td><?php foreach($tables as $table) echo esc_html($table.': '.($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table))?'OK':'missing').' ');?></td></tr><tr><th>Webhook / HOTTOK</th><td><?php echo Settings::get('hmp_webhook_enabled')?'enabled':'disabled';?> / <?php echo Settings::get('hmp_hottok')?'configured':'missing';?></td></tr><tr><th>Next grace cron</th><td><?php echo esc_html(($next=wp_next_scheduled(Lifecycle::GRACE_HOOK))?gmdate('c',$next):'not scheduled');?></td></tr><tr><th>Failed / grace</th><td><?php echo esc_html($this->events->counts_by_status()['failed'].' / '.$this->activations->count_status('grace'));?></td></tr></tbody></table><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="hmp_run_grace"><?php wp_nonce_field('hmp_run_grace');submit_button(__('Run grace expirations','hotmart-memberpress-pro'),'secondary');?></form></div><?php }
}
